source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-assets'
gem 'maruku'
gem 'kramdown'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages', '~> 28'
gem 'github-pages-health-check'
gem 'jekyll-mentions'
gem 'jemoji'